name: WorldGuard
main: com.sk89q.worldguard.bukkit.WorldGuardPlugin
version: "${internalVersion}"
api-version: "1.21.7"
dependencies:
  server:
    FastAsyncWorldEdit:
      load: BEFORE
      required: true
      join-classpath: true